/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deli;

import javax.swing.JFileChooser;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Image;
import java.io.File;
/**
 *
 * @author Dollars
 */
public class Customer extends javax.swing.JFrame {

    public static String Ship;
    public static LocalDate myObj = LocalDate.now();
    public static String invoiceID;
    public static String status;
    public static String OrderID;
    public static String ProductCode;
    public String s;
    public int attach;
    public String ee;
    public int e;


    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address = new javax.swing.JTextArea();
        Lname = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        Country = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        QuantityProduct = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Des = new javax.swing.JTextArea();
        Attachment = new javax.swing.JButton();
        Picture = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Submit = new javax.swing.JButton();
        Province = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        Shipping_Fee = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        at = new javax.swing.JTextField();
        m1 = new deli.M();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FnameKeyTyped(evt);
            }
        });
        getContentPane().add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 64, 138, -1));

        Address.setColumns(20);
        Address.setRows(5);
        jScrollPane1.setViewportView(Address);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 178, -1, -1));

        Lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LnameKeyTyped(evt);
            }
        });
        getContentPane().add(Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 98, 138, -1));
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 138, 234, -1));

        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });
        Phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PhoneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PhoneKeyTyped(evt);
            }
        });
        getContentPane().add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 293, 170, -1));

        Country.setText("Thailand");
        Country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryActionPerformed(evt);
            }
        });
        getContentPane().add(Country, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 398, 170, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FirstName***");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 67, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 141, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LastName***");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 101, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 214, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone***");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 296, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Provinec");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 346, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Country");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 404, -1, -1));

        QuantityProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityProductActionPerformed(evt);
            }
        });
        QuantityProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantityProductKeyTyped(evt);
            }
        });
        getContentPane().add(QuantityProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 438, 170, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantity Product Weigth***");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 441, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Description");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 539, -1, -1));

        Des.setColumns(20);
        Des.setRows(5);
        jScrollPane2.setViewportView(Des);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 518, -1, -1));

        Attachment.setText("Attachment");
        Attachment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttachmentActionPerformed(evt);
            }
        });
        getContentPane().add(Attachment, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 629, -1, -1));

        Picture.setForeground(new java.awt.Color(255, 255, 255));
        Picture.setText("Picture");
        getContentPane().add(Picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 172, 103));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 596, -1, -1));

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 669, -1, -1));

        Province.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chiang Rai", "Chiang Mai", "Tak", "Nakhon Sawan", "Nan", "Phichit", "Phitsanulok", "Phetchabun", "Phrae", "Mae Hong Son", "Lampang", "Lamphun", "Sukhothai", "Uttaradit", "Uthai Thani", "Phayao", "Bangkok", "Kanchanaburi", "Chanthaburi", "Chachoengsao", "Chon Buri", "Chai Nat", "Trat", "Nakhon Nayok", "Nakhon Pathom", "Nonthaburi", "Pathum Thani", "Prachuap Khiri Khan", "Prachin Buri", "Phra Nakhon Si Ayutthaya", "Phetchaburi", "Rayong", "Ratchaburi", "Lop Buri", "Samut Prakan", "Samut Songkhram", "Samut Sakhon", "Saraburi", "Sing Buri", "Suphan Buri", "Ang Thong", "Sa Kaeo", "Kalasin", "Khon Kaen", "Chaiyaphum", "Yasothon", "Nakhon Phanom", "Nakhon Ratchasima", "Buri Ram", "Maha Sarakham", "Roi Et", "Loei", "Si Sa Ket", "Sakon Nakhon", "Surin", "Nong Khai", "Udon Thani", "Ubon Ratchathani", "Mukdahan", "Amnat Charoen", "Nong Bua Lam Phu", "Krabi", "Chumphon", "Trang", "Nakhon Si Thammarat", "Narathiwat", "Pattani", "Phangnga", "Phatthalung", "Phuket", "Yala", "Ranong", "Songkhla", "Satun", "Surat Thani" }));
        Province.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ProvinceItemStateChanged(evt);
            }
        });
        getContentPane().add(Province, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 343, 234, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Shipping_Fee");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 479, -1, 26));

        Shipping_Fee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Shipping_Fee.setForeground(new java.awt.Color(255, 255, 255));
        Shipping_Fee.setText("0");
        getContentPane().add(Shipping_Fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 478, 170, 26));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 17, -1, -1));

        btnCheck.setText("Check Status ");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 163, -1));
        getContentPane().add(at, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 0, -1));

        m1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 730));

        label.setText("jLabel10");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryActionPerformed


    }//GEN-LAST:event_CountryActionPerformed
    File file;
    String result = "";

    private void QuantityProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityProductActionPerformed
        String ea = QuantityProduct.getText();
        if (ea.isEmpty()) {
            Shipping_Fee.setText("0");
        } 
        else {
            double a = Double.parseDouble(ea);
           
            
            /////////////////////////////////////////////////////////
            int come = 0;
            if (a == 0) {
                come = 0;
            } else if (a >= 0.1 && a <= 0.25) {
                come = 42;
            } else if (a > 0.25 && a <= 0.5) {
                come = 52;
            } else if (a > 0.5 && a <= 1.0) {
                come = 65;
            } else if (a > 1.0 && a <= 2.0) {
                come = 75;
            } else if (a > 2.0 && a <= 5.0) {
                come = 92;
            } else if (a > 5.0 && a <= 10.0) {
                come = 117;
            } else if (a > 10.0 && a <= 15.0) {
                come = 193;
            } else if (a > 15.0) {
                come = 236;
            }
             if (a > 30) {
                JOptionPane.showMessageDialog(this, "Quantity prohibit exceed 30 ", "ERROR", JOptionPane.ERROR_MESSAGE);
                come = 0;
            }
            
            String Aftersum = String.valueOf(come);
            Shipping_Fee.setText(Aftersum);
          
        }
       


    }//GEN-LAST:event_QuantityProductActionPerformed
    public ImageIcon ResizeImage(String imgPath) {
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(Picture.getWidth(), Picture.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
    private void AttachmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttachmentActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*,IMAGE", "jpg", "gif", "png");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            Picture.setIcon(ResizeImage(path));
            s = path;
        }
        attach += 1;
        ee = String.valueOf(attach);
        at.setText(ee);
        e = Integer.parseInt(ee);
    }//GEN-LAST:event_AttachmentActionPerformed


    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        Ship = Shipping_Fee.getText();
        myObj = LocalDate.now();
       
      
        ResultSet rs;
        DB_Connect db = new DB_Connect();
        try {
        if (!Fname.getText().isEmpty() && !Lname.getText().isEmpty() && !Phone.getText().isEmpty()
                    && !QuantityProduct.getText().isEmpty() ) {
        
        String INcustomer = String.format("INSERT INTO customers(cus_fname,cus_lname,cus_email,cus_Phone,cus_Address,cus_Province,cus_Country)Values('%s','%s','%s','%s','%s','%s','%s')",
                Fname.getText(), Lname.getText(), Email.getText(), Address.getText(), Phone.getText(), Province.getSelectedItem(), Country.getText() );
        

            if (new DB_Connect().execute(INcustomer)) {
                JOptionPane.showMessageDialog(this, "Succes");

            } else {
                JOptionPane.showMessageDialog(this, "Fail", "", JOptionPane.ERROR_MESSAGE);
            }

            String INorders = String.format("INSERT INTO `orders` (Employee_ID,Shippers_Date,Shippers_ID,Status,Customer)"
                    + " Values((SELECT E_ID FROM `employee` WHERE  E_ID = 10),(NOW()),(SELECT ID FROM `Shippers` WHERE ID = 4),'Invoiced',(SELECT cus_ID FROM `customers` ORDER BY cus_ID DESC LIMIT 1))");

            if (new DB_Connect().execute(INorders)) {
                System.out.println("success");

            } else {
                System.out.println("fail");
            }

            String INinvoice = String.format("INSERT INTO invoice(Order_ID,Invoice_Date,Shipping_Fee)Values((SELECT Order_ID FROM `orders`ORDER BY Order_ID DESC LIMIT 1 ),'%s','%s')", myObj, Ship);

            if (new DB_Connect().execute(INinvoice)) {
                System.out.println("success");

            } else {
                System.out.println("fail");

            }

            try {
                if(e >= 1){
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/deli", "root", "");
                PreparedStatement ps = con.prepareStatement("insert into `product`(Description,Attachment) values(?,?)");
                InputStream is = new FileInputStream(new File(s));
                ps.setString(1, Des.getText());
                ps.setBlob(2, is);
                ps.executeUpdate();
                }else if(e <= 0){
                 Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/deli", "root", "");
                PreparedStatement ps1 = con1.prepareStatement("insert into `product`(Description) values(?)");
                ps1.setString(1, Des.getText());
                ps1.executeUpdate();
                }

            } catch (Exception e) {
                e.printStackTrace();
            }


            String INordersDetial = String.format("INSERT INTO `order_detail` (Order_ID,Product_Code,Quantity,Attachment,Weight,Price)"
                    + " Values((SELECT Order_ID FROM `orders`ORDER BY Order_ID DESC LIMIT 1),(SELECT Product_code FROM `product`ORDER BY Product_code DESC LIMIT 1),'1',(SELECT Attachment FROM `product`ORDER BY Product_code DESC LIMIT 1),'%s','%s')", QuantityProduct.getText(), Shipping_Fee.getText());

            if (new DB_Connect().execute(INordersDetial)) {
                System.out.println("success");

            } else {
                System.out.println("fail");

            }

            String SEinvoice = "SELECT * FROM `invoice` ORDER BY Invoice_ID  ";

            rs = db.getResultSet(SEinvoice);
            while (rs.next()) {
                invoiceID = rs.getString("Invoice_ID");

            }

            String SEorders = "SELECT * FROM `orders` ORDER BY Order_ID DESC LIMIT 1 ";

            rs = db.getResultSet(SEorders);
            while (rs.next()) {
                OrderID = rs.getString("Order_ID");

            }

            String SEproduct = "SELECT * FROM `product` ";

            rs = db.getResultSet(SEproduct);
            while (rs.next()) {

                ProductCode = rs.getString("Product_Code");

            }

        
            new Invoice().setVisible(true);
            dispose();} 
        else {
                JOptionPane.showMessageDialog(this, "Please fill out the required information completely.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {

        }


    }//GEN-LAST:event_SubmitActionPerformed

    private void QuantityProductKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityProductKeyTyped

    }//GEN-LAST:event_QuantityProductKeyTyped

    private void PhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_PhoneKeyTyped

    private void FnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FnameKeyTyped
        char enter = evt.getKeyChar();
        if ((Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_FnameKeyTyped

    private void LnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LnameKeyTyped
        char enter = evt.getKeyChar();
        if ((Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_LnameKeyTyped

    private void ProvinceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ProvinceItemStateChanged
        Country.setText("Thailand");
    }//GEN-LAST:event_ProvinceItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Main().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        new CheckTrack().setVisible(true);

    }//GEN-LAST:event_btnCheckActionPerformed

    private void PhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneKeyPressed
        //Set 10 max

        String phonenumber = Phone.getText();
        int lenght = phonenumber.length();

        char c = evt.getKeyChar();

        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            if (lenght < 10) {
                    Phone.setEditable(true);
                    
            }else{
                Phone.setEditable(false);
            }

        }else{
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
            Phone.setEditable(true);
                    
            }else{
                Phone.setEditable(false);
            }
            
        }

    }//GEN-LAST:event_PhoneKeyPressed

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Address;
    private javax.swing.JButton Attachment;
    private javax.swing.JTextField Country;
    private javax.swing.JTextArea Des;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField Phone;
    private javax.swing.JLabel Picture;
    private javax.swing.JComboBox<String> Province;
    private javax.swing.JTextField QuantityProduct;
    private javax.swing.JLabel Shipping_Fee;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField at;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label;
    private deli.M m1;
    // End of variables declaration//GEN-END:variables

    private static class toBeSet {

        private static void setIcon(ImageIcon icon) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public toBeSet() {
        }
    }
}
