/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deli;

import java.awt.Event;

/**
 *
 * @author Dollars
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Invoice
     */
    public Invoice() {
        initComponents();
//         txtInvoiceID.setBackground(new java.awt.Color(0, 0, 0, 1));
//         txtOrderD1.setBackground(new java.awt.Color(0, 0, 0, 1));
//         txtShipping_Fee.setBackground(new java.awt.Color(0, 0, 0, 1));
        L_ShippingFee.setText(Customer.Ship);
        L_InvoiceDate.setText(Customer.myObj.toString());
        L_InvoiceID.setText(Customer.invoiceID);
        L_OrderID.setText(Customer.OrderID);
        L_ProCode.setText(Customer.ProductCode);

    
      
    }
    @Override
    public boolean action(Event evt, Object what) {
        return super.action(evt, what); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        J_ID = new javax.swing.JLabel();
        J_OrderID = new javax.swing.JLabel();
        J_Date = new javax.swing.JLabel();
        J_Shipping = new javax.swing.JLabel();
        Next = new javax.swing.JLabel();
        L_ProCode = new javax.swing.JLabel();
        L_InvoiceID = new javax.swing.JLabel();
        L_OrderID = new javax.swing.JLabel();
        L_InvoiceDate = new javax.swing.JLabel();
        J_ProductCode = new javax.swing.JLabel();
        L_ShippingFee = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        m3 = new deli.M();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dollars\\Desktop\\Icon\\Invoice.png")); // NOI18N
        jLabel1.setText("Invoice");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        J_ID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        J_ID.setForeground(new java.awt.Color(255, 255, 255));
        J_ID.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dollars\\Desktop\\Icon\\ID.png")); // NOI18N
        J_ID.setText("ID :");
        getContentPane().add(J_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, -1));

        J_OrderID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        J_OrderID.setForeground(new java.awt.Color(255, 255, 255));
        J_OrderID.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dollars\\Desktop\\Icon\\Order.png")); // NOI18N
        J_OrderID.setText("Order ID :");
        getContentPane().add(J_OrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 150, 110, -1));

        J_Date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        J_Date.setForeground(new java.awt.Color(255, 255, 255));
        J_Date.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dollars\\Desktop\\Icon\\Date.png")); // NOI18N
        J_Date.setText("Date :");
        getContentPane().add(J_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        J_Shipping.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        J_Shipping.setForeground(new java.awt.Color(255, 255, 255));
        J_Shipping.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dollars\\Desktop\\Icon\\Ship.png")); // NOI18N
        J_Shipping.setText("Shipping Fee :");
        getContentPane().add(J_Shipping, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        Next.setBackground(new java.awt.Color(0, 0, 0,1));
        Next.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        Next.setForeground(new java.awt.Color(255, 255, 255));
        Next.setText("     Submit");
        Next.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NextMousePressed(evt);
            }
        });
        getContentPane().add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 100, 30));

        L_ProCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_ProCode.setForeground(new java.awt.Color(255, 255, 255));
        L_ProCode.setText("15");
        getContentPane().add(L_ProCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 120, -1));

        L_InvoiceID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_InvoiceID.setForeground(new java.awt.Color(255, 255, 255));
        L_InvoiceID.setText("1234");
        getContentPane().add(L_InvoiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 120, -1));

        L_OrderID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_OrderID.setForeground(new java.awt.Color(255, 255, 255));
        L_OrderID.setText("1234");
        getContentPane().add(L_OrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 120, -1));

        L_InvoiceDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_InvoiceDate.setForeground(new java.awt.Color(255, 255, 255));
        L_InvoiceDate.setText("Date");
        getContentPane().add(L_InvoiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 180, -1));

        J_ProductCode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        J_ProductCode.setForeground(new java.awt.Color(255, 255, 255));
        J_ProductCode.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dollars\\Desktop\\Icon\\Product.png")); // NOI18N
        J_ProductCode.setText("Product Code :");
        getContentPane().add(J_ProductCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        L_ShippingFee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_ShippingFee.setForeground(new java.awt.Color(255, 255, 255));
        L_ShippingFee.setText("15");
        getContentPane().add(L_ShippingFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 120, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,1));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 100, 30));
        getContentPane().add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -60, 470, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMousePressed

        new Manage().setVisible(true);
        dispose();

    }//GEN-LAST:event_NextMousePressed

    private void NextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseClicked

    }//GEN-LAST:event_NextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel J_Date;
    private javax.swing.JLabel J_ID;
    private javax.swing.JLabel J_OrderID;
    private javax.swing.JLabel J_ProductCode;
    private javax.swing.JLabel J_Shipping;
    private javax.swing.JLabel L_InvoiceDate;
    private javax.swing.JLabel L_InvoiceID;
    private javax.swing.JLabel L_OrderID;
    public static javax.swing.JLabel L_ProCode;
    public static javax.swing.JLabel L_ShippingFee;
    private javax.swing.JLabel Next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private deli.M m3;
    // End of variables declaration//GEN-END:variables
}
