/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deli;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.sql.ResultSet;

/**
 *
 * @author Dollars
 */
public class loginV extends javax.swing.JFrame {

    public static String user;

    /**
     * Creates new form loginV
     */
    public loginV() {
        initComponents();
        Show.setVisible(false);
        txtPass.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtUser.setBackground(new java.awt.Color(0, 0, 0, 1));
        jib_Incorpass.setVisible(false);
        UIManager.put("OptionPane.messageFont", new java.awt.Font("TH Baijam", 1, 16));

        try {
            new DB_Connect().connectDB();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Show = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        txtUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jib_Incorpass = new javax.swing.JLabel();
        SignIn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        m1 = new deli.M();
        m11 = new Menu.M1();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("K e e l e r ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 68));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dollars\\Desktop\\Icon\\Back.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 300, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dollars\\Desktop\\Icon\\Close Window Icon.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, 36));

        Show.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dollars\\Desktop\\Icon\\EyeNo.png")); // NOI18N
        Show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ShowMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ShowMouseReleased(evt);
            }
        });
        getContentPane().add(Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, -1, -1));

        Close.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dollars\\Desktop\\Icon\\EyePass.png")); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CloseMouseReleased(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Admin Login");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Password : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 110, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 100, 30));

        txtPass.setFont(new java.awt.Font("Sylfaen", 0, 17)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setBorder(null);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 240, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 250, 10));

        txtUser.setFont(new java.awt.Font("Sylfaen", 0, 17)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setBorder(null);
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 240, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 250, 10));

        jib_Incorpass.setForeground(new java.awt.Color(255, 0, 51));
        jib_Incorpass.setText("*Wrong Password Or Username");
        getContentPane().add(jib_Incorpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 180, -1));

        SignIn.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        SignIn.setForeground(new java.awt.Color(255, 255, 255));
        SignIn.setText("    Sign In");
        SignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SignInMousePressed(evt);
            }
        });
        getContentPane().add(SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 88, 28));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,1));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));
        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 440, 480));
        getContentPane().add(m11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void ShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseClicked

    }//GEN-LAST:event_ShowMouseClicked

    private void ShowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMousePressed

    }//GEN-LAST:event_ShowMousePressed

    private void ShowMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowMouseReleased

    private void CloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMousePressed
        Show.setVisible(true);
        Close.setVisible(false);
        txtPass.setEchoChar((char) (0));
    }//GEN-LAST:event_CloseMousePressed

    private void CloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseReleased
        Show.setVisible(false);
        Close.setVisible(true);
        txtPass.setEchoChar('*');
    }//GEN-LAST:event_CloseMouseReleased

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        txtUser.requestFocus();
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        txtUser.requestFocus();
    }//GEN-LAST:event_txtUserActionPerformed
    int count = 0; //
    private void SignInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInMousePressed
        String sql = String.format("SELECT*FROM `employee` WHERE E_email = '%s' AND E_SSn = '%s';", txtUser.getText(), txtPass.getText());
        user = txtUser.getText();
        DB_Connect db = new DB_Connect();
        try {
            ResultSet rs = db.getResultSet(sql);
            if (rs.next()) {
                new Main().setVisible(true);
                JOptionPane.showMessageDialog(this, "Correct", "", JOptionPane.ERROR_MESSAGE);
                setVisible(false);
            } else {
                count++;
                if (count != 4) {
                    JOptionPane.showMessageDialog(this, "Incorrect Username or Password.Try Again (" + count + "/3 times)");
                    jib_Incorpass.setVisible(true);
                    txtUser.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(this, "Sorry. You Enter Incorrect Username or Password more than 3 times");
                    System.exit(0);;

                }

            }
        }
        
        catch(Exception e){
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_SignInMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
           FlatLightLaf.setup();

      
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Show;
    private javax.swing.JLabel SignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jib_Incorpass;
    private deli.M m1;
    private Menu.M1 m11;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
